name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com/"
  NEXAUTH_URL: "https://fake.com"
  GITHUB_CLIENT_ID: "GITHUB_CLIENT_ID"
  GITHUB_CLIENT_SECRET: "GITHUB_CLIENT_SECRET" 
  UPSTASH_REDIS_REST_URL: "https://fake.com/"
  UPSTASH_REDIS_REST_TOKEN: "UPSTASH_REDIS_REST_TOKEN" 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Line
        run: npm run lint
